### ISSUE TITLE
Data Daerah Tujuan

### ISSUE THREAD

**Issue by syauqiahmd** [syauqiahmd/Rujukan-Pasien#28]
- [x] Data untuk Provinsi dan Kota tujuan untuk semua dikalimantan soalnya bisa ditempuh jalan darat

**Comment by FaruqRahmadani** [comment]
jadi kena ini sekalimantanan?

**Comment by syauqiahmd** [comment]
iyun gin ruq, soalnya ke kalbar bisa aja kan ada kemunkinan sedikit soalnya masih bisa ditempuh jalan darat

**Comment by FaruqRahmadani** [comment]
dikerjakan di #31

**Comment by FaruqRahmadani** [comment]
kalo sdh fix ku close lah?

**Comment by syauqiahmd** [comment]
wokeh, hnyar mau ku closekan wkwkkw
