### ISSUE TITLE
Teks jumlah total di laporan periode

### ISSUE THREAD

**Issue by FaruqRahmadani** [syauqiahmd/Rujukan-Pasien#50]
### Hengpon jadoel
![image](https://user-images.githubusercontent.com/11961119/48975107-afd3db80-f0a4-11e8-9e84-6b2ce6840849.png)

pina ada yg salah, di apai lah itu?

**Comment by FaruqRahmadani** [comment]
itu dasar kebawah atau harusnya kehiga?

**Comment by syauqiahmd** [comment]
harusnya kehiga pang, tpi mun panjang dasarnya jdi kebawah
wait lah ku akali,
