### ISSUE TITLE
Revisi 3.0

### ISSUE THREAD

**Issue by FaruqRahmadani** [syauqiahmd/Rujukan-Pasien#69]
- [x] Judul laporan
- [x] Validasi NIK Pasien
- [x] Tambah data Kecamatan
- [x] Di cetak laporan tambah tanda tangan dokter
- [x] catatan dokter di menu rujukan

**Comment by syauqiahmd** [comment]
judul laporan ??? yg dimna ruq, master ?

**Comment by syauqiahmd** [comment]
trus yg dicetak laporan tambah tanda tangan dokter, itu yg laporan mana ruq ?

**Comment by FaruqRahmadani** [comment]
eh ada lagi rasanya, dokter tu ada catatanya pas rujukan

**Comment by syauqiahmd** [comment]
fixed on #71
